// ============================================
// PDF Export Composable
// ============================================

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { MealPlan } from '@/types'

export function usePDFExport() {
  function exportToPDF(mealPlan: MealPlan) {
    const doc = new jsPDF()

    // Title
    doc.setFontSize(20)
    doc.text('AI 맞춤 식단 플래너', 105, 20, { align: 'center' })

    // Profile Summary
    doc.setFontSize(12)
    const profile = mealPlan.profile
    let y = 35

    doc.text('사용자 프로필', 20, y)
    y += 7

    doc.setFontSize(10)
    const profileInfo = [
      `성별: ${profile.gender === 'male' ? '남성' : '여성'}  |  나이: ${profile.age}세  |  키: ${profile.height}cm  |  체중: ${profile.weight}kg`,
      `목표: ${profile.goal}  |  활동량: ${profile.activity_level}`,
      `알레르기: ${profile.allergies.length > 0 ? profile.allergies.join(', ') : '없음'}`,
      `건강 제약: ${profile.health_conditions.length > 0 ? profile.health_conditions.join(', ') : '없음'}`,
      `예산: ${mealPlan.total_budget.toLocaleString()}원 (${profile.budget_type})`
    ]

    profileInfo.forEach(info => {
      doc.text(info, 20, y)
      y += 5
    })

    y += 5

    // Daily Meal Plans
    mealPlan.days.forEach((day) => {
      // Check if we need a new page
      if (y > 250) {
        doc.addPage()
        y = 20
      }

      // Day Header
      doc.setFontSize(14)
      doc.text(`Day ${day.day}`, 20, y)
      y += 7

      // Meal Table
      const mealData = day.meals.map(meal => [
        meal.meal_type,
        meal.recipe.name,
        `${Math.round(meal.recipe.nutrition.calories_kcal)} kcal`,
        `${meal.recipe.estimated_cost.toLocaleString()}원`
      ])

      autoTable(doc, {
        startY: y,
        head: [['식사', '메뉴', '칼로리', '비용']],
        body: mealData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] },
        styles: { fontSize: 9, cellPadding: 3 },
        margin: { left: 20, right: 20 }
      })

      y = (doc as any).lastAutoTable.finalY + 5

      // Daily Nutrition Summary
      doc.setFontSize(10)
      const nutrition = day.total_nutrition
      const nutritionText = [
        `일일 영양: 칼로리 ${Math.round(nutrition.calories_kcal)}kcal  |  `,
        `단백질 ${Math.round(nutrition.protein_g)}g  |  `,
        `탄수화물 ${Math.round(nutrition.carbs_g)}g  |  `,
        `지방 ${Math.round(nutrition.fat_g)}g`
      ].join('')
      doc.text(nutritionText, 20, y)

      doc.setFontSize(9)
      y += 5
      doc.text(`일일 비용: ${day.total_cost.toLocaleString()}원`, 20, y)
      y += 10
    })

    // Average Weekly Nutrition
    if (y > 240) {
      doc.addPage()
      y = 20
    }

    doc.setFontSize(12)
    doc.text('주간 평균 영양', 20, y)
    y += 7

    doc.setFontSize(10)
    const avg = mealPlan.avg_daily_nutrition
    const avgData = [
      ['칼로리', `${Math.round(avg.calories_kcal)} kcal`],
      ['단백질', `${Math.round(avg.protein_g)} g`],
      ['탄수화물', `${Math.round(avg.carbs_g)} g`],
      ['지방', `${Math.round(avg.fat_g)} g`]
    ]

    autoTable(doc, {
      startY: y,
      body: avgData,
      theme: 'plain',
      styles: { fontSize: 10 },
      margin: { left: 20 }
    })

    y = (doc as any).lastAutoTable.finalY + 7

    // Budget Summary
    doc.text(`총 비용: ${mealPlan.total_cost.toLocaleString()}원 / ${mealPlan.total_budget.toLocaleString()}원`, 20, y)

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text('AI Meal Planner - Generated by Claude 3.5 Haiku', 105, 285, { align: 'center' })
    doc.text(`생성일: ${new Date(mealPlan.created_at).toLocaleDateString('ko-KR')}`, 105, 290, { align: 'center' })

    // Save PDF
    const filename = `meal-plan-${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(filename)
  }

  return {
    exportToPDF
  }
}
